#############################################################################
# Makefile for building: ModifiedADIOS
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Wed Sep 19 20:10:28 2012
# Project:  ModifiedADIOS.pro
# Template: app
# Command: $(QMAKE) -o Makefile ModifiedADIOS.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -g -Wall -W -O2 -D_REENTRANT  
CXXFLAGS = -pipe -g -Wall -W -O2 -pedantic -ansi -D_REENTRANT  
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -Iutils -Imaths -Imaths/tnt
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS)  -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = RDSGraph.h \
		RDSNode.h \
		BasicSymbol.h \
		SearchPath.h \
		utils/Stringable.h \
		SpecialLexicons.h \
		SignificantPattern.h \
		EquivalenceClass.h \
		maths/special.h \
		utils/TimeFuncs.h
SOURCES = main.cpp \
		RDSGraph.cpp \
		RDSNode.cpp \
		BasicSymbol.cpp \
		SearchPath.cpp \
		utils/Stringable.cpp \
		SpecialLexicons.cpp \
		SignificantPattern.cpp \
		EquivalenceClass.cpp \
		maths/special.cpp \
		utils/MiscUtils.cpp \
		utils/TimeFuncs.cpp
OBJECTS = main.o \
		RDSGraph.o \
		RDSNode.o \
		BasicSymbol.o \
		SearchPath.o \
		Stringable.o \
		SpecialLexicons.o \
		SignificantPattern.o \
		EquivalenceClass.o \
		special.o \
		MiscUtils.o \
		TimeFuncs.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = 
OBJMOC = 
DIST	   = ModifiedADIOS.pro
QMAKE_TARGET = ModifiedADIOS
DESTDIR  = 
TARGET   = ModifiedADIOS

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: ModifiedADIOS.pro  /usr/share/qt3/mkspecs/default/qmake.conf 
	$(QMAKE) -o Makefile ModifiedADIOS.pro
qmake: 
	@$(QMAKE) -o Makefile ModifiedADIOS.pro

dist: 
	@mkdir -p .tmp/ModifiedADIOS && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/ModifiedADIOS/ && ( cd `dirname .tmp/ModifiedADIOS` && $(TAR) ModifiedADIOS.tar ModifiedADIOS && $(GZIP) ModifiedADIOS.tar ) && $(MOVE) `dirname .tmp/ModifiedADIOS`/ModifiedADIOS.tar.gz . && $(DEL_FILE) -r .tmp/ModifiedADIOS

mocclean:
uiclean:

yaccclean:
lexclean:
clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

main.o: main.cpp utils/MiscUtils.h \
		RDSGraph.h \
		maths/special.h \
		utils/TimeFuncs.h \
		RDSNode.h \
		ADIOSUtils.h \
		ParseTree.h \
		maths/tnt/array2d.h \
		LexiconUnit.h \
		maths/tnt/array1d.h \
		utils/Stringable.h \
		BasicSymbol.h \
		SpecialLexicons.h \
		SignificantPattern.h \
		EquivalenceClass.h \
		SearchPath.h

RDSGraph.o: RDSGraph.cpp RDSGraph.h \
		utils/TimeFuncs.h \
		RDSNode.h \
		ADIOSUtils.h \
		maths/special.h \
		utils/MiscUtils.h \
		ParseTree.h \
		maths/tnt/array2d.h \
		LexiconUnit.h \
		maths/tnt/array1d.h \
		utils/Stringable.h \
		BasicSymbol.h \
		SpecialLexicons.h \
		SignificantPattern.h \
		EquivalenceClass.h \
		SearchPath.h

RDSNode.o: RDSNode.cpp RDSNode.h \
		maths/tnt/array2d.h \
		LexiconUnit.h \
		ADIOSUtils.h \
		maths/tnt/array1d.h \
		utils/Stringable.h \
		BasicSymbol.h \
		SpecialLexicons.h \
		SignificantPattern.h \
		EquivalenceClass.h \
		SearchPath.h

BasicSymbol.o: BasicSymbol.cpp BasicSymbol.h \
		LexiconUnit.h \
		utils/Stringable.h

SearchPath.o: SearchPath.cpp SearchPath.h \
		utils/Stringable.h

Stringable.o: utils/Stringable.cpp utils/Stringable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stringable.o utils/Stringable.cpp

SpecialLexicons.o: SpecialLexicons.cpp SpecialLexicons.h \
		LexiconUnit.h \
		utils/Stringable.h

SignificantPattern.o: SignificantPattern.cpp SignificantPattern.h \
		LexiconUnit.h \
		utils/Stringable.h

EquivalenceClass.o: EquivalenceClass.cpp EquivalenceClass.h \
		LexiconUnit.h \
		utils/Stringable.h

special.o: maths/special.cpp maths/special.h \
		maths/Constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o special.o maths/special.cpp

MiscUtils.o: utils/MiscUtils.cpp utils/MiscUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MiscUtils.o utils/MiscUtils.cpp

TimeFuncs.o: utils/TimeFuncs.cpp utils/TimeFuncs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TimeFuncs.o utils/TimeFuncs.cpp

####### Install

install:  

uninstall:  

