#############################################################################
# Makefile for building: ModifiedADIOS
# Generated by qmake (2.01a) (Qt 4.8.1) on: Thu Feb 28 13:26:53 2013
# Project:  ModifiedADIOS.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile ModifiedADIOS.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT
CFLAGS        = -m64 -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -pedantic -ansi -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I. -Iutils -Imaths -Imaths/tnt
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)    
AR            = ar cqs
RANLIB        = 
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		RDSGraph.cpp \
		RDSNode.cpp \
		BasicSymbol.cpp \
		SearchPath.cpp \
		utils/Stringable.cpp \
		SpecialLexicons.cpp \
		SignificantPattern.cpp \
		EquivalenceClass.cpp \
		maths/special.cpp \
		utils/MiscUtils.cpp \
		utils/TimeFuncs.cpp 
OBJECTS       = main.o \
		RDSGraph.o \
		RDSNode.o \
		BasicSymbol.o \
		SearchPath.o \
		Stringable.o \
		SpecialLexicons.o \
		SignificantPattern.o \
		EquivalenceClass.o \
		special.o \
		MiscUtils.o \
		TimeFuncs.o
DESTDIR       = 
TARGET        = ModifiedADIOS

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core

####### Compile

main.o: main.cpp utils/MiscUtils.h \
		RDSGraph.h \
		RDSNode.h \
		maths/tnt/array2d.h \
		maths/tnt/array1d.h \
		LexiconUnit.h \
		utils/Stringable.h \
		ADIOSUtils.h \
		BasicSymbol.h \
		SpecialLexicons.h \
		SignificantPattern.h \
		EquivalenceClass.h \
		SearchPath.h \
		maths/special.h \
		ParseTree.h \
		utils/TimeFuncs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

RDSGraph.o: RDSGraph.cpp RDSGraph.h \
		RDSNode.h \
		maths/tnt/array2d.h \
		maths/tnt/array1d.h \
		LexiconUnit.h \
		utils/Stringable.h \
		ADIOSUtils.h \
		BasicSymbol.h \
		SpecialLexicons.h \
		SignificantPattern.h \
		EquivalenceClass.h \
		SearchPath.h \
		maths/special.h \
		utils/MiscUtils.h \
		ParseTree.h \
		utils/TimeFuncs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RDSGraph.o RDSGraph.cpp

RDSNode.o: RDSNode.cpp RDSNode.h \
		maths/tnt/array2d.h \
		maths/tnt/array1d.h \
		LexiconUnit.h \
		utils/Stringable.h \
		ADIOSUtils.h \
		BasicSymbol.h \
		SpecialLexicons.h \
		SignificantPattern.h \
		EquivalenceClass.h \
		SearchPath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RDSNode.o RDSNode.cpp

BasicSymbol.o: BasicSymbol.cpp BasicSymbol.h \
		LexiconUnit.h \
		utils/Stringable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BasicSymbol.o BasicSymbol.cpp

SearchPath.o: SearchPath.cpp SearchPath.h \
		utils/Stringable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SearchPath.o SearchPath.cpp

Stringable.o: utils/Stringable.cpp utils/Stringable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stringable.o utils/Stringable.cpp

SpecialLexicons.o: SpecialLexicons.cpp SpecialLexicons.h \
		LexiconUnit.h \
		utils/Stringable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpecialLexicons.o SpecialLexicons.cpp

SignificantPattern.o: SignificantPattern.cpp SignificantPattern.h \
		LexiconUnit.h \
		utils/Stringable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SignificantPattern.o SignificantPattern.cpp

EquivalenceClass.o: EquivalenceClass.cpp EquivalenceClass.h \
		LexiconUnit.h \
		utils/Stringable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EquivalenceClass.o EquivalenceClass.cpp

special.o: maths/special.cpp maths/special.h \
		maths/Constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o special.o maths/special.cpp

MiscUtils.o: utils/MiscUtils.cpp utils/MiscUtils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MiscUtils.o utils/MiscUtils.cpp

TimeFuncs.o: utils/TimeFuncs.cpp utils/TimeFuncs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TimeFuncs.o utils/TimeFuncs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

